// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmsawndyowokpvqgeudt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtc2F3bmR5b3dva3B2cWdldWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTk4MDcsImV4cCI6MjA2NjgzNTgwN30.S9yBpop3srxCxw6HCakXz1zNaeL2rk5Y0bBv-EXyGjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});